### ISSUE TITLE
accessing current time on VFS database throws bad function error

### ISSUE THREAD

**Issue by rhashimoto** [rhashimoto/wa-sqlite#43]
On the [demo](https://rhashimoto.github.io/wa-sqlite/demo/), accessing the current time, e.g. with:

`SELECT datetime('now');`

works on the default filesystem but fails with any custom VFS with:

```
RuntimeError: null function or function signature mismatch
    at https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.wasm:wasm-function[659]:0x38ed2
    at https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.wasm:wasm-function[1176]:0x57047
    at https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.wasm:wasm-function[503]:0x26f89
    at https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.wasm:wasm-function[1177]:0x5709b
    at https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.wasm:wasm-function[530]:0x2b26c
    at G (https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.mjs:17:311)
    at https://rhashimoto.github.io/wa-sqlite/dist/wa-sqlite.mjs:110:235
    at Object.step (https://rhashimoto.github.io/wa-sqlite/src/sqlite-api.js:562:28)
    at https://rhashimoto.github.io/wa-sqlite/src/examples/tag.js:37:28
    at async HTMLButtonElement. (https://rhashimoto.github.io/wa-sqlite/demo/index.js:121:23)
```

A custom VFS is supposed to borrow the default time method [here](https://github.com/rhashimoto/wa-sqlite/blob/83ee9037ebe27fdfabfe8bc20cf91c54a1ad375c/src/libvfs.c#L92) but this is apparently broken.

**Comment by rhashimoto** [comment]
`SELECT datetime('now')` works on Safari but the added unit test fails. So the bug appears fixed but apparently there's a browser-specific bug in the test.
